spring:
  application:
    name: banking
  datasource:
    # TODO: replace with real database credentials
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

jwt:
  # TODO: Change this secret key to a secure one
  secret: super_duper_secret_key_unhackable_very_secure_wow
  expiration: 86400000  # 24 hours in milliseconds
  cookie-name: jwt_token

server:
  port: 8080
  servlet:
    context-path:

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Rate limiting configuration
rate-limit:
  capacity: 2000
  refill:
    tokens: 2000
    duration: 1

react-app:
  url: http://localhost:3000
