spring:
  application:
    name: banking
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariCorePool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select * from information_schema.tables limit 1

jwt:
  # TODO: Change this secret key to a secure one
  secret: super_duper_secret_key_unhackable_very_secure_wow
  expiration: 86400000  # 24 hours in milliseconds
  cookie-name: jwt_token

server:
  port: 8080
  servlet:
    context-path:

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Rate limiting configuration
rate-limit:
  capacity: 2000
  refill:
    tokens: 2000
    duration: 1

react-app:
  # TODO: pull service name from environment variable
  url: http://frontend:3000

# Actuator and Metrics configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
    otlp:
      endpoint: http://opentelemetry-collector:4317

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
